/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WitchHouse2026.glb --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import witchHouseUrl from '../assets/artwork/WitchHouse2026.glb?url'

export function WitchHouse(props) {
  const { nodes, materials } = useGLTF(witchHouseUrl)
  return (
    <group {...props} dispose={null}>
      <group position={[7.144, 0.297, -6.539]} scale={[37.254, 96.46, 53.915]}>
        <mesh geometry={nodes.pasted__backwall.geometry} material={materials.mainwalls} position={[0, 0.04, -0.065]} rotation={[1.571, Math.PI / 2, 0]} scale={[8, 15, 20]} />
        <mesh geometry={nodes.pasted__floor.geometry} material={materials['bathroom floor.001']} scale={[0.973, 1, 0.983]} />
        <mesh geometry={nodes.pasted__leftwall.geometry} material={materials.mainwalls} position={[-0.1, 0.04, -0.001]} rotation={[0, 0, 1.571]} scale={[8, 15, 13]} />
        <mesh geometry={nodes['pasted__leftwall_(1)'].geometry} material={materials.bathwalls} position={[-0.098, 0.04, -0.001]} rotation={[0, 0, 1.571]} scale={[8, 15, 13]} />
        <mesh geometry={nodes['pasted__leftwall_(4)'].geometry} material={materials.bathwalls} position={[0.099, 0.04, -0.001]} rotation={[0, 0, 1.571]} scale={[8, 15, 13]} />
        <mesh geometry={nodes['pasted__leftwall_(2)'].geometry} material={materials.bathwalls} position={[0.002, 0.04, 0.064]} rotation={[1.571, Math.PI / 2, 0]} scale={[8, 15, 19.636]} />
        <mesh geometry={nodes['pasted__leftwall_(3)'].geometry} material={materials.bathwalls} position={[0.002, 0.04, -0.064]} rotation={[1.571, Math.PI / 2, 0]} scale={[8, 15, 19.636]} />
        <mesh geometry={nodes.pasted__rightwall.geometry} material={materials.mainwalls} position={[0.1, 0.04, 0]} rotation={[0, 0, 1.571]} scale={[8, 15, 13]} />
      </group>
      <group position={[-11.959, 0.299, 3.182]} scale={[156.37, 96.46, 96.46]}>
        <group position={[0.061, 0, -0.101]} scale={[0.386, 1, 0.559]}>
          <mesh geometry={nodes.pasted__pasted__backwall.geometry} material={materials.mainwalls} position={[0, 0.04, -0.065]} rotation={[1.571, Math.PI / 2, 0]} scale={[8, 15, 20]} />
          <mesh geometry={nodes.pasted__pasted__floor.geometry} material={materials.mainfloor} position={[-0.004, 0, 0]} scale={[19.995, 15, 13]} />
          <mesh geometry={nodes.pasted__pasted__leftwall.geometry} material={materials.mainwalls} position={[-0.1, 0.04, 0]} rotation={[0, 0, 1.571]} scale={[8, 15, 13]} />
        </group>
      </group>
      <group position={[1.23, 0.298, 3.185]} scale={96.46}>
        <mesh geometry={nodes.toiletback.geometry} material={materials['sink and toilet']} position={[0.096, 0.012, -0.122]} scale={[0.626, 2.406, 1.914]} />
        <mesh geometry={nodes.toiletbottom.geometry} material={materials['sink and toilet']} position={[0.08, 0.007, -0.123]} scale={[1.052, 0.465, 0.818]} />
        <mesh geometry={nodes.toiletseat.geometry} material={materials['sink and toilet']} position={[0.08, 0.017, -0.123]} scale={[1.151, 0.081, 0.895]} />
        <mesh geometry={nodes.toilettop.geometry} material={materials['sink and toilet']} position={[0.08, 0.014, -0.123]} scale={[1.287, 0.149, 1]} />
      </group>
      <group position={[1.23, 0.298, 3.185]} scale={96.46}>
        <mesh geometry={nodes.backwall.geometry} material={materials.mainwalls} position={[0, 0.04, -0.065]} rotation={[1.571, Math.PI / 2, 0]} scale={[8, 15, 20]} />
        <mesh geometry={nodes.floor.geometry} material={materials.mainfloor} scale={[20, 15, 13]} />
        <mesh geometry={nodes.ceiling.geometry} material={materials.chair} position={[0, 0.079, -0.037]} rotation={[0, 0, 3.142]} scale={[20, 15, 21.016]} />
        <mesh geometry={nodes.frontwall.geometry} material={materials.mainwalls} position={[0, 0.04, 0.065]} rotation={[1.571, Math.PI / 2, 0]} scale={[8, 15, 20]} />
        <mesh geometry={nodes.leftwall.geometry} material={materials.mainwalls} position={[-0.1, 0.04, 0]} rotation={[0, 0, 1.571]} scale={[8, 15, 13]} />
        <mesh geometry={nodes.rightwall.geometry} material={materials.mainwalls} position={[0.1, 0.04, 0]} rotation={[0, 0, 1.571]} scale={[8, 15, 13]} />
      </group>
      <group position={[-5.21, 0, -7.42]} rotation={[0, Math.PI / 2, 0]} scale={0.9}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001 1']} position={[0, 0.515, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Grid.geometry} material={materials['Material.002 1']} position={[2.46, 2.172, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[196.02, 100, 167.38]} />
        <mesh geometry={nodes.Sphere.geometry} material={materials.Lit} position={[1.24, 2.225, -0.107]} rotation={[Math.PI / 2, 0, -0.076]} scale={100} />
      </group>
      <group position={[2.752, -0.772, 6.788]} rotation={[-0.192, 0.246, 0.635]} scale={1.263}>
        <mesh geometry={nodes.Cube.geometry} material={materials.table} position={[1.19, 1.03, 0.13]} rotation={[Math.PI / 2, 0, -2.936]} scale={100} />
      </group>
      <group position={[3.064, -0.567, 6.713]} rotation={[-0.266, 0.339, 0.713]} scale={1.263}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.table} position={[0.03, 1.03, -0.17]} rotation={[Math.PI / 2, 0, 0.29]} scale={100} />
      </group>
      <group position={[7.853, 2.564, 8.321]} rotation={[0.08, 0, 0]} scale={17.948}>
        <group position={[0, 0.025, 0]}>
          <mesh geometry={nodes.pasted__pCylinder119_1.geometry} material={materials.broombristles} />
          <mesh geometry={nodes.pasted__pCylinder119_2.geometry} material={materials.broom} />
        </group>
      </group>
      <group position={[5.792, 0.276, 1.616]} scale={17.948}>
        <mesh geometry={nodes.Big_bottle.geometry} material={materials.potionbottle} position={[-0.192, 0.14, -0.284]} rotation={[Math.PI / 2, 0, -2.121]} scale={30.045} />
        <mesh geometry={nodes.Big_bottle_cork.geometry} material={materials.potion_extrainsides} position={[-0.192, 0.14, -0.284]} rotation={[Math.PI / 2, 0, -2.121]} scale={30.045} />
        <mesh geometry={nodes.Big_bottle_fill.geometry} material={materials.potion_extrainsides} position={[-0.192, 0.14, -0.284]} rotation={[Math.PI / 2, 0, -2.121]} scale={30.045} />
        <mesh geometry={nodes.Big_bottle_label.geometry} material={materials.potion_extrainsides} position={[-0.192, 0.14, -0.284]} rotation={[Math.PI / 2, 0, -2.121]} scale={30.045} />
        <mesh geometry={nodes.Big_potion.geometry} material={materials.potion_extrainsides} position={[0.187, 0.215, 0.181]} rotation={[Math.PI / 2, 0, -2.09]} scale={22.867} />
        <mesh geometry={nodes.Big_potion_cork.geometry} material={materials.potion_extrainsides} position={[0.187, 0.215, 0.181]} rotation={[Math.PI / 2, 0, -2.09]} scale={22.867} />
        <mesh geometry={nodes.Big_potion_fill.geometry} material={materials.potion} position={[0.187, 0.215, 0.181]} rotation={[Math.PI / 2, 0, -2.09]} scale={22.867} />
        <mesh geometry={nodes.Big_potion_label.geometry} material={materials.potion_extrainsides} position={[0.187, 0.215, 0.181]} rotation={[Math.PI / 2, 0, -2.09]} scale={22.867} />
        <mesh geometry={nodes.Medium_potion.geometry} material={materials.potion_extrainsides} position={[-0.604, 0.003, 0.331]} rotation={[Math.PI / 2, 0, 0.477]} scale={46.964} />
        <mesh geometry={nodes.Medium_potion_cork.geometry} material={materials.potion_extrainsides} position={[-0.604, 0.003, 0.331]} rotation={[Math.PI / 2, 0, 0.477]} scale={46.964} />
        <mesh geometry={nodes.Medium_potion_fill.geometry} material={materials.potion_extrainsides} position={[-0.604, 0.003, 0.331]} rotation={[Math.PI / 2, 0, 0.477]} scale={46.964} />
        <mesh geometry={nodes.Medium_potion_label.geometry} material={materials.potion_extrainsides} position={[-0.604, 0.003, 0.331]} rotation={[Math.PI / 2, 0, 0.477]} scale={46.964} />
        <mesh geometry={nodes.Small_bottle.geometry} material={materials.potion_extrainsides} position={[0, 0, -0.431]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Small_bottle_cork.geometry} material={materials.potion_extrainsides} position={[0, 0, -0.431]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Small_bottle_fill.geometry} material={materials['Fill liquid']} position={[0, 0, -0.431]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Small_bottle_label.geometry} material={materials.potion_extrainsides} position={[0, 0, -0.431]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Small_potion.geometry} material={materials.window} position={[-0.147, 0.14, -0.551]} rotation={[Math.PI / 2, 0, -2.013]} scale={52.623} />
        <mesh geometry={nodes.Small_potion_cork.geometry} material={materials.potion_extrainsides} position={[-0.147, 0.14, -0.551]} rotation={[Math.PI / 2, 0, -2.013]} scale={52.623} />
        <mesh geometry={nodes.Small_potion_fill.geometry} material={materials.potion_extrainsides} position={[-0.147, 0.14, -0.551]} rotation={[Math.PI / 2, 0, -2.013]} scale={52.623} />
        <mesh geometry={nodes.Small_potion_label.geometry} material={materials.potion_extrainsides} position={[-0.147, 0.14, -0.551]} rotation={[Math.PI / 2, 0, -2.013]} scale={52.623} />
        <mesh geometry={nodes.Special_potion.geometry} material={materials.potion_extrainsides} position={[-0.175, 0.161, -0.341]} rotation={[Math.PI / 2, 0, 0.614]} scale={36.564} />
        <mesh geometry={nodes.Special_potion_cork.geometry} material={materials.potion_extrainsides} position={[-0.175, 0.161, -0.341]} rotation={[Math.PI / 2, 0, 0.614]} scale={36.564} />
        <mesh geometry={nodes.Special_potion_fill.geometry} material={materials.potion_extrainsides} position={[-0.175, 0.161, -0.341]} rotation={[Math.PI / 2, 0, 0.614]} scale={36.564} />
        <mesh geometry={nodes.Special_potion_label.geometry} material={materials.potion_extrainsides} position={[-0.175, 0.161, -0.341]} rotation={[Math.PI / 2, 0, 0.614]} scale={36.564} />
      </group>
      <group position={[-6.68, 2.72, 7.916]} rotation={[1.436, -0.003, 0.328]} scale={3.564}>
        <mesh geometry={nodes.Paper_1.geometry} material={materials.paper} position={[0.245, -0.003, 0.038]} rotation={[0.133, 0, 0]} scale={0.025} />
        <mesh geometry={nodes.Paper2.geometry} material={materials.paper} position={[0.002, -0.056, 0.008]} scale={0.025} />
        <mesh geometry={nodes['Paper2_(1)'].geometry} material={materials.paper} position={[0.137, -0.056, 0.017]} rotation={[0, 0, 0.484]} scale={0.025} />
        <mesh geometry={nodes.Paper3.geometry} material={materials.paper} position={[-0.093, -0.15, -0.006]} scale={0.025} />
        <mesh geometry={nodes['Paper3_(1)'].geometry} material={materials.paper} position={[0.128, -0.284, -0.006]} scale={0.025} />
      </group>
      <group position={[-0.814, 0.424, -8.714]} rotation={[1.46, 0.064, -0.338]} scale={3.564}>
        <mesh geometry={nodes.Paper_2.geometry} material={materials.paper} position={[0.245, -0.003, 0.038]} rotation={[0.133, 0, 0]} scale={0.025} />
        <mesh geometry={nodes.Paper2_1.geometry} material={materials.paper} position={[0.002, -0.056, 0.008]} scale={0.025} />
        <mesh geometry={nodes['Paper2_(1)_1'].geometry} material={materials.paper} position={[0.137, -0.056, 0.017]} rotation={[0, 0, 0.484]} scale={0.025} />
        <mesh geometry={nodes.Paper3_1.geometry} material={materials.paper} position={[-0.093, -0.18, -0.006]} scale={0.025} />
      </group>
      <group position={[0.173, 0.58, -7.696]} rotation={[1.538, 0.014, -2.141]} scale={3.564}>
        <mesh geometry={nodes.Paper_3.geometry} material={materials.paper} position={[0.245, -0.003, 0.038]} rotation={[0.133, 0, 0]} scale={0.025} />
        <mesh geometry={nodes.Paper2_2.geometry} material={materials.paper} position={[0.002, -0.056, 0.008]} scale={0.025} />
        <mesh geometry={nodes['Paper2_(1)_2'].geometry} material={materials.paper} position={[0.137, -0.056, 0.017]} rotation={[0, 0, 0.484]} scale={0.025} />
        <mesh geometry={nodes.Paper3_2.geometry} material={materials.paper} position={[-0.093, -0.18, -0.006]} scale={0.025} />
      </group>
      <group position={[-1.007, 0.594, -6.818]} rotation={[1.538, 0.014, -1.208]} scale={3.564}>
        <mesh geometry={nodes.Paper_4.geometry} material={materials.paper} position={[0.245, -0.003, 0.038]} rotation={[0.133, 0, 0]} scale={0.025} />
        <mesh geometry={nodes.Paper2_3.geometry} material={materials.paper} position={[0.002, -0.056, 0.008]} scale={0.025} />
        <mesh geometry={nodes['Paper2_(1)_3'].geometry} material={materials.paper} position={[0.137, -0.056, 0.017]} rotation={[0, 0, 0.484]} scale={0.025} />
        <mesh geometry={nodes.Paper3_3.geometry} material={materials.paper} position={[-0.093, -0.18, -0.006]} scale={0.025} />
      </group>
      <group position={[0.056, 0.576, -5.733]} rotation={[1.545, 0.008, -2.13]} scale={3.564}>
        <mesh geometry={nodes.Paper_5.geometry} material={materials.paper} position={[0.245, -0.003, 0.038]} rotation={[0.133, 0, 0]} scale={0.025} />
        <mesh geometry={nodes.Paper2_4.geometry} material={materials.paper} position={[0.002, 0.222, 0.042]} scale={0.025} />
        <mesh geometry={nodes['Paper2_(1)_4'].geometry} material={materials.paper} position={[0.281, 0.218, 0.017]} rotation={[0, 0, 0.484]} scale={0.025} />
        <mesh geometry={nodes.Paper3_4.geometry} material={materials.paper} position={[0.052, -0.18, -0.006]} scale={0.025} />
      </group>
      <group position={[-0.931, 0.599, -4.52]} rotation={[1.545, 0.008, -1.58]} scale={3.564}>
        <mesh geometry={nodes.Paper_6.geometry} material={materials.paper} position={[0.245, -0.003, 0.038]} rotation={[0.133, 0, 0]} scale={0.025} />
        <mesh geometry={nodes.Paper2_5.geometry} material={materials.paper} position={[0.002, 0.222, 0.042]} scale={0.025} />
        <mesh geometry={nodes['Paper2_(1)_5'].geometry} material={materials.paper} position={[0.281, 0.218, 0.017]} rotation={[0, 0, 0.484]} scale={0.025} />
        <mesh geometry={nodes.Paper3_5.geometry} material={materials.paper} position={[0.052, -0.18, -0.006]} scale={0.025} />
      </group>
      <group position={[-0.895, 2.833, -2.359]} rotation={[0, -0.323, 0]} scale={6.955}>
        <mesh geometry={nodes.Lantern_01.geometry} material={materials['standardSurface1.002']} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Lantern_01_glass.geometry} material={materials.lanternlight} rotation={[Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group position={[2.791, 2.785, -8.116]} rotation={[0, -0.323, 0]} scale={6.955}>
        <mesh geometry={nodes.Lantern_01_1.geometry} material={materials['standardSurface1.002']} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Lantern_01_glass_1.geometry} material={materials.lanternlight} rotation={[Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group position={[10.469, 2.667, -8.763]} rotation={[0, -1.34, 0]} scale={6.955}>
        <mesh geometry={nodes.Lantern_01_2.geometry} material={materials['standardSurface1.002']} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Lantern_01_glass_2.geometry} material={materials.lanternlight} rotation={[Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group position={[10.627, -2.85, 18.556]} scale={2.696}>
        {/* <mesh geometry={nodes.Victorian_Bookcase_Tall.geometry} material={materials['bookshelf 1']} position={[0, 0, -0.005]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Books_1.geometry} material={materials['bookshelf 1']} position={[0, 0, -0.001]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Books_2.geometry} material={materials['bookshelf 1']} position={[0, 0, -0.004]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Books_3.geometry} material={materials['bookshelf 1']} position={[0, -0.001, -0.007]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Books_4.geometry} material={materials['bookshelf 1']} position={[-0.041, 0.005, -0.026]} rotation={[Math.PI / 2, 0.595, Math.PI / 2]} scale={1.516} />
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Books_5.geometry} material={materials['bookshelf 1']} position={[-0.046, 0.004, -0.013]} rotation={[0, 0, -Math.PI]} scale={1.481} />
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Books_6.geometry} material={materials['bookshelf 1']} position={[-0.042, 0.005, -0.02]} rotation={[0, 0, -Math.PI]} scale={1.424} />
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Books_7.geometry} material={materials['bookshelf 1']} position={[-0.042, 0.004, -0.033]} rotation={[0.037, -0.327, -3.112]} scale={1.601} />
          <mesh geometry={nodes.Victorian_Bookcase_Tall_Corner.geometry} material={materials.broom} />
        </mesh> */}
      </group>
      <mesh geometry={nodes.bookshelf001.geometry} material={materials.bookshelf} position={[9.734, 3.852, 6.525]} scale={[167.563, 711.114, 503.472]} />
      <mesh geometry={nodes.chair1.geometry} material={materials.chair} position={[-4.375, 1.555, 4.91]} rotation={[0, -0.761, 0]} scale={[176.069, 34.391, 176.069]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.cauldron} position={[2.039, 1.911, 6.28]} rotation={[1.567, 0, 0]} scale={[180.097, 177.601, 154.594]} />
      <mesh geometry={nodes.diningtable.geometry} material={materials.table} position={[-5.845, 2.314, 6.841]} scale={[222.162, 27.059, 222.162]}>
        <mesh geometry={nodes.tableleg.geometry} material={materials.doors} position={[0, -0.039, 0]} scale={[0.124, 3.5, 0.124]} />
      </mesh>
      <mesh geometry={nodes.doortobathroom.geometry} material={materials.doors} position={[7.484, 3.309, -3.049]} scale={[267.959, 595.255, 33.444]}>
        <mesh geometry={nodes['doorknob_(2)'].geometry} material={materials.doorknobs} position={[0.003, 0, 0.012]} scale={[0.002, 0.001, 0.012]}>
          <mesh geometry={nodes.e.geometry} material={materials.doorknobs} position={[0, 0.01, -0.47]} rotation={[-1.528, 0, 0]} scale={[0.554, 0.216, 0.554]} />
        </mesh>
        <mesh geometry={nodes['doorknob_(3)'].geometry} material={materials.doorknobs} position={[-0.003, 0, -0.013]} rotation={[3.141, 0, 0]} scale={[0.002, 0.001, 0.012]}>
          <mesh geometry={nodes.e_1.geometry} material={materials.doorknobs} position={[0.001, 0.011, -0.47]} rotation={[-1.528, 0, 0]} scale={[0.554, 0.216, 0.554]} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.doortobedroom.geometry} material={materials.doors} position={[-5.312, 3.31, -3.053]} scale={[267.959, 595.255, 33.444]}>
        <mesh geometry={nodes.doorknob.geometry} material={materials.doorknobs} position={[0.003, 0, 0.012]} scale={[0.002, 0.001, 0.012]}>
          <mesh geometry={nodes.e_2.geometry} material={materials.doorknobs} position={[0, 0.01, -0.47]} rotation={[-1.528, 0, 0]} scale={[0.554, 0.216, 0.554]} />
        </mesh>
        <mesh geometry={nodes['doorknob_(1)'].geometry} material={materials.doorknobs} position={[-0.003, 0, -0.013]} rotation={[3.141, 0, 0]} scale={[0.002, 0.001, 0.012]}>
          <mesh geometry={nodes.e_3.geometry} material={materials.doorknobs} position={[0.001, 0.011, -0.47]} rotation={[-1.528, 0, 0]} scale={[0.554, 0.216, 0.554]} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.frontdoor.geometry} material={materials.doors} position={[-8.446, 3.31, -0.429]} rotation={[0, 1.57, 0]} scale={[267.959, 595.255, 33.444]}>
        <mesh geometry={nodes.doorknob_1.geometry} material={materials.doorknobs} position={[0.003, 0, 0.011]} scale={[0.002, 0.001, 0.012]}>
          <mesh geometry={nodes.e_4.geometry} material={materials.doorknobs} position={[0, 0.01, -0.47]} rotation={[-1.528, 0, 0]} scale={[0.554, 0.216, 0.554]} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.potionliquid.geometry} material={materials.potion} position={[-6.231, 2.671, 5.828]} scale={[45.242, 45.192, 45.242]} />
      <mesh geometry={nodes['potionliquid_(1)'].geometry} material={materials.potion} position={[2.138, -0.359, 6.271]} scale={[195.358, 142.424, 195.358]} />
      <mesh geometry={nodes.rug.geometry} material={materials.rug} position={[2.039, 0.281, 6.01]} scale={[5.433, 0.054, 5.433]} />
      <mesh geometry={nodes.potionbook.geometry} material={materials['book cover']} position={[-4.65, 2.895, 6.528]} rotation={[0.056, 0.038, 3.139]} scale={[100, 45.428, 73.883]}>
        <mesh geometry={nodes.potionbook001.geometry} material={materials['book cover']} position={[0, -0.004, 0.011]} scale={[1, 0.255, 0.999]} />
        <mesh geometry={nodes.potionbook002.geometry} material={materials.bookpages} scale={[0.88, 0.611, 0.837]} />
        <mesh geometry={nodes.potionbook003.geometry} material={materials.bookpages} position={[0, -0.005, 0.01]} scale={[0.866, 0.164, 0.8]} />
      </mesh>
      <mesh geometry={nodes.potionbottle.geometry} material={materials.potionbottle} position={[-6.241, 2.611, 5.86]} scale={[48.314, 49.324, 48.314]} />
      <mesh geometry={nodes.sink.geometry} material={materials['sink and toilet']} position={[4.185, 1.807, -4.393]} scale={[142.367, 283.788, 213.416]}>
        <group position={[-0.02, -0.005, 0.036]} scale={[0.678, 0.34, 0.452]}>
          <mesh geometry={nodes.pCylinder1.geometry} material={materials.tv} position={[0.022, 0.034, -0.078]} scale={[0.066, 0.538, 0.066]} />
          <mesh geometry={nodes.pCylinder2.geometry} material={materials.tv} position={[0.025, 0.04, -0.078]} rotation={[0, 0, -1.51]} scale={[0.06, 0.328, 0.056]} />
          <mesh geometry={nodes.pCylinder3.geometry} material={materials.tv} position={[0.028, 0.039, -0.078]} rotation={[0, 0, -3.018]} scale={[0.054, 0.097, 0.053]} />
        </group>
      </mesh>
      <mesh geometry={nodes.television.geometry} material={materials.tv} position={[1.232, 5.297, -2.8]} scale={[327.995, 196.909, 3.951]} />
      <mesh geometry={nodes.television_stand.geometry} material={materials.wooden} position={[1.231, 1.574, -2.283]} scale={[547.858, 247.703, 134.421]} />
      <mesh geometry={nodes['television_stand_(1)'].geometry} material={materials['wooden alt']} position={[2.412, 1.569, -7.95]} rotation={[0, -1.57, 0]} scale={[385.534, 247.703, 164.034]} />
      <mesh geometry={nodes.window.geometry} material={materials.doors} position={[10.855, 5.297, 1.091]} rotation={[0, 1.57, 0]} scale={[412.604, 383.761, 33.444]} />
      <mesh geometry={nodes.window003.geometry} material={materials.window} position={[10.855, 5.297, 1.091]} rotation={[0, 1.57, 0]} scale={[319.914, 297.551, 9.769]} />
      <group position={[0.418, 2.832, -2.552]} rotation={[0, Math.PI / 4, 0]} scale={3.731}>
        <mesh geometry={nodes.Ball_Pen_Gold.geometry} material={materials.doorknobs} />
        <mesh geometry={nodes.Ball_Pen_Gold_1.geometry} material={materials.tv} />
        <mesh geometry={nodes.Ball_Pen_Gold_2.geometry} material={materials.Silver} />
        <mesh geometry={nodes.Ball_Pen_Gold_3.geometry} material={materials.Outline} />
      </group>
      <group position={[-0.357, 0.431, -6.307]} rotation={[0, Math.PI / 4, 0]} scale={3.731}>
        <mesh geometry={nodes.Ball_Pen_Gold.geometry} material={materials.doorknobs} />
        <mesh geometry={nodes.Ball_Pen_Gold_1.geometry} material={materials.tv} />
        <mesh geometry={nodes.Ball_Pen_Gold_2.geometry} material={materials.Silver} />
        <mesh geometry={nodes.Ball_Pen_Gold_3.geometry} material={materials.Outline} />
      </group>
      <group position={[-5.467, 2.617, 5.615]} rotation={[-Math.PI, 0.883, Math.PI]} scale={3.731}>
        <mesh geometry={nodes.Ball_Pen_Gold.geometry} material={materials.doorknobs} />
        <mesh geometry={nodes.Ball_Pen_Gold_1.geometry} material={materials.tv} />
        <mesh geometry={nodes.Ball_Pen_Gold_2.geometry} material={materials.Silver} />
        <mesh geometry={nodes.Ball_Pen_Gold_3.geometry} material={materials.Outline} />
      </group>
      <mesh geometry={nodes.candle.geometry} material={materials.candle} position={[9.263, 4.164, 6.185]} rotation={[0, 0.789, 0]} scale={158.318} />
    </group>
  )
}

useGLTF.preload(witchHouseUrl)
